/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockPriceFeedInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getMaxPriceX96"
      | "getMinPriceX96"
      | "maxPriceX96"
      | "minPriceX96"
      | "setMaxPriceX96"
      | "setMinPriceX96"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getMaxPriceX96",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinPriceX96",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxPriceX96",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minPriceX96",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxPriceX96",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinPriceX96",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getMaxPriceX96",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinPriceX96",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxPriceX96",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minPriceX96",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxPriceX96",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinPriceX96",
    data: BytesLike
  ): Result;
}

export interface MockPriceFeed extends BaseContract {
  connect(runner?: ContractRunner | null): MockPriceFeed;
  waitForDeployment(): Promise<this>;

  interface: MockPriceFeedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMaxPriceX96: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getMinPriceX96: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  maxPriceX96: TypedContractMethod<[], [bigint], "view">;

  minPriceX96: TypedContractMethod<[], [bigint], "view">;

  setMaxPriceX96: TypedContractMethod<
    [_maxPriceX96: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinPriceX96: TypedContractMethod<
    [_minPriceX96: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMaxPriceX96"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMinPriceX96"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxPriceX96"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minPriceX96"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setMaxPriceX96"
  ): TypedContractMethod<[_maxPriceX96: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinPriceX96"
  ): TypedContractMethod<[_minPriceX96: BigNumberish], [void], "nonpayable">;

  filters: {};
}
