/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockEFCInterface extends Interface {
  getFunction(
    nameOrSignature: "referrerTokens" | "setReferrerToken"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "referrerTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setReferrerToken",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "referrerTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReferrerToken",
    data: BytesLike
  ): Result;
}

export interface MockEFC extends BaseContract {
  connect(runner?: ContractRunner | null): MockEFC;
  waitForDeployment(): Promise<this>;

  interface: MockEFCInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  referrerTokens: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint]],
    "view"
  >;

  setReferrerToken: TypedContractMethod<
    [
      arg0: AddressLike,
      _memberTokenId: BigNumberish,
      _connectorTokenId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "referrerTokens"
  ): TypedContractMethod<[arg0: AddressLike], [[bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "setReferrerToken"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      _memberTokenId: BigNumberish,
      _connectorTokenId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
